### PR TITLE
refactor, bugfixing, updating api, maintaining

### PR DESCRIPTION
**Pull request by samuel-hxs**
Removed explicit versions for python modules.
Replaced modules for use with pycharm community.

First pull request ever so critic welcome.

### CODE REVIEW

**Comment by Brutus5000** [comment]
Never ever remove the explicit versions. We had so many go-live issues due to new library versions which broke. You may update them, but not remove them.

**Comment by samuel-hxs** [comment]
Okay Explicit versions are back.
But i updatet them. 

I will work on this pull request for about a month or until i think it is okay.
I think i do this wrong here. 

Things i want to work on:
Add QAI as module for use with pip.
Updating API's for '!streams' command.
Large and small refactoring.  
Adding more tests.
Adding Doxygen or Python native dcumentation

**Comment by Sheeo** [comment]
A better solution is to start using [pipenv](https://github.com/pypa/pipenv#pipenv-python-development-workflow-for-humans), which will handle dependency lockdowns for us.

Sounds good with the upcoming work @samuel-hxs 👍 If you don't mind; please do integrate `pipenv` and update the PR. The other changes look good and ready to merge!

**Comment by samuel-hxs** [comment]
I need to check if everything is in order.
Would like to make some tests and verify that QAI works as intended.
 
I do this because i made some changes without verifying them.
Also i do not quit understand how pipenv works.

Should be done until Saturday afternoon.

**Comment by Brutus5000** [comment]
The Pipfile.lock looks like relevant data for a local machine. If this is the case, we should add it to gitignore.

**Comment by samuel-hxs** [comment]
Im trying to understand how to use pipenv and in my understanding it is necessary.
Im working at verifying and testing my changes at the moment.

**Comment by samuel-hxs** [comment]
Should not work! 
I need to make changes to reflect the refactoring and the difference of python2 modules and python3 modules.

Also is it out of scope to update the streaming API's?

**Comment by Brutus5000** [comment]
A recommendation: don't make too many changes in one PR. If you are happy with a certain state, we can set it up on the test server so you can test it in a real environment.

**Comment by samuel-hxs** [comment]
Well then anything to do for this to get acceptet?

**Comment by Bra1nwash3d** [comment]
Best case if ofc. to bug Sheeo into giving you permissions to this repository, so you can push directly, without PR. For now I'll just merge your changes

**Pull request merged**
